// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1YjBliKeNyFux3Z5qLbScBbCNkV-IeQ',
    appId: '1:982199820441:web:cb2b8872d39be689c3d808',
    messagingSenderId: '982199820441',
    projectId: 'newsapp-91e83',
    authDomain: 'newsapp-91e83.firebaseapp.com',
    storageBucket: 'newsapp-91e83.firebasestorage.app',
    measurementId: 'G-FQ5Q11R8YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYZjyW_AAVy7iz7uCrETDVR7RYAF75Ss',
    appId: '1:982199820441:android:2769eb9b58bec6cac3d808',
    messagingSenderId: '982199820441',
    projectId: 'newsapp-91e83',
    storageBucket: 'newsapp-91e83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiVDccchO_Saw4xN2lmpKMPHH9V2SJtXM',
    appId: '1:982199820441:ios:cdd16599b866de26c3d808',
    messagingSenderId: '982199820441',
    projectId: 'newsapp-91e83',
    storageBucket: 'newsapp-91e83.firebasestorage.app',
    iosBundleId: 'com.example.flutterMyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiVDccchO_Saw4xN2lmpKMPHH9V2SJtXM',
    appId: '1:982199820441:ios:cdd16599b866de26c3d808',
    messagingSenderId: '982199820441',
    projectId: 'newsapp-91e83',
    storageBucket: 'newsapp-91e83.firebasestorage.app',
    iosBundleId: 'com.example.flutterMyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1YjBliKeNyFux3Z5qLbScBbCNkV-IeQ',
    appId: '1:982199820441:web:43a27408479961c6c3d808',
    messagingSenderId: '982199820441',
    projectId: 'newsapp-91e83',
    authDomain: 'newsapp-91e83.firebaseapp.com',
    storageBucket: 'newsapp-91e83.firebasestorage.app',
    measurementId: 'G-TGJZ7YQQF9',
  );
}
